### ISSUE TITLE
visual height bug

### ISSUE THREAD

**Issue by nonfreegithub** [fennelfox/mcl_heart_animations#2]
mod version:

master branch commit a061f422c7092bd975fba34b1fd6b6c72d97b159

![screenshot_20230910_135127](https://github.com/fennelfox/mcl_heart_animations/assets/122187904/1d4be3d0-1122-44b7-8e45-2248cd375121)

**Comment by fennelfox** [comment]
Lol, seems I forgot to test it in something other than creative... I'll try to fix this soon.

**Comment by fennelfox** [comment]
Fixed with 5cfbb02
